name: Quality assurance

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v2

      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v2

      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Run tests
        run: pnpm test

  linter:
    name: Linter
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v2

      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Run linter
        run: pnpm lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v2

      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Build
        run: pnpm build
