name: Quality assurance

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Run tests
        run: pnpm test

  linter:
    name: Linter
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Run linter
        run: pnpm lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Build
        run: pnpm build
